import test from 'node:test'; import assert from 'node:assert/strict';
import { createNeed, createHelperProfile, transitionNeed, publicNeedView } from '../domain/model.mjs';
import { scoreMatch, rankHelpers } from '../domain/matching.mjs';

test('external needs always start unclaimed and private',()=>{ const n=createNeed({origin:'external',location:{label:'Naperville',lat:41.75,lng:-88.15}}); assert.equal(n.status,'unclaimed'); assert.equal(n.privacy.contactVisible,false); assert.equal(n.privacy.exactAddressVisible,false); });
test('native need starts verified but must explicitly open',()=>{ const n=createNeed({origin:'native'}); assert.equal(n.status,'verified'); assert.equal(transitionNeed(n,'open').status,'open'); });
test('invalid state jump is blocked',()=>{ const n=createNeed({origin:'external'}); assert.throws(()=>transitionNeed(n,'open'),/Invalid need transition/); });
test('matching respects radius and ranks stronger fit first',()=>{ const n={...createNeed({category:'yard',helpType:'paid',location:{lat:41.75,lng:-88.15}}),status:'open'}; const near=createHelperProfile({displayName:'Near',home:{lat:41.751,lng:-88.15},radiusMiles:3,categories:['yard'],helpTypes:['paid'],reliability:.95,verified:true}); const far=createHelperProfile({displayName:'Far',home:{lat:42,lng:-88.15},radiusMiles:3,categories:['yard'],helpTypes:['paid'],verified:true}); assert.equal(scoreMatch(n,far).eligible,false); assert.equal(rankHelpers(n,[far,near])[0].helper.displayName,'Near'); });

test('public projection suppresses exact coordinates and requester fields',()=>{ const n=createNeed({origin:'native',location:{label:'Near downtown',lat:41.77,lng:-88.14,precision:'exact'},requester:{userId:'secret-user'}}); const v=publicNeedView(n); assert.equal('lat' in v.location,false); assert.equal('lng' in v.location,false); assert.equal('requester' in v,false); assert.equal('privacy' in v,false); });
test('paid hourly task below helper minimum is ineligible',()=>{ const n={...createNeed({category:'yard',helpType:'paid',compensation:{amount:15,unit:'hour'},location:{lat:41.75,lng:-88.15}}),status:'open'}; const h=createHelperProfile({home:{lat:41.751,lng:-88.15},radiusMiles:3,categories:['yard'],helpTypes:['paid'],minimumHourly:25,verified:true}); assert.equal(scoreMatch(n,h).eligible,false); });
test('volunteer task is not sent to paid-only helper',()=>{ const n={...createNeed({category:'yard',helpType:'volunteer',location:{lat:41.75,lng:-88.15}}),status:'open'}; const h=createHelperProfile({home:{lat:41.751,lng:-88.15},categories:['yard'],helpTypes:['paid'],verified:true}); assert.equal(scoreMatch(n,h).eligible,false); });

test('verified-but-not-open need cannot match',()=>{ const n=createNeed({origin:'native',category:'yard',location:{lat:41.75,lng:-88.15}}); const h=createHelperProfile({home:{lat:41.751,lng:-88.15},categories:['yard'],verified:true}); assert.equal(n.status,'verified'); assert.equal(scoreMatch(n,h).eligible,false); });
test('unverified helper cannot receive matches',()=>{ const n={...createNeed({origin:'native',category:'yard',location:{lat:41.75,lng:-88.15}}),status:'open'}; const h=createHelperProfile({home:{lat:41.751,lng:-88.15},categories:['yard'],verified:false}); assert.equal(scoreMatch(n,h).eligible,false); });
