export const demoNeeds = [
  { id:'need_demo_yard', origin:'native', category:'yard', title:'Help bag fallen branches', description:'Looking for a neighbor to help gather and bag branches for about an hour.', helpType:'paid', compensation:{amount:30,currency:'USD',unit:'total'}, location:{label:'South Naperville',lat:41.735,lng:-88.145,precision:'neighborhood'}, time:{start:'2026-09-05T09:00:00-05:00',end:'2026-09-05T12:00:00-05:00'}, urgency:'normal' },
  { id:'need_demo_move', origin:'native', category:'moving', title:'Move a dresser downstairs', description:'One dresser, one flight of stairs. A second person will be available.', helpType:'paid', compensation:{amount:25,currency:'USD',unit:'total'}, location:{label:'Central Naperville',lat:41.772,lng:-88.153,precision:'neighborhood'}, time:{start:'2026-09-05T10:00:00-05:00',end:'2026-09-05T13:00:00-05:00'}, urgency:'normal' },
  { id:'need_demo_grocery', origin:'native', category:'pickup_delivery', title:'Grocery pickup for older neighbor', description:'Pickup is already paid. Need a neighbor to bring two grocery bags nearby.', helpType:'volunteer', location:{label:'North Naperville',lat:41.795,lng:-88.147,precision:'neighborhood'}, time:{flexible:true}, urgency:'high' },
  { id:'need_demo_external', origin:'external', source:{provider:'public_web',url:'https://example.org/community-post'}, category:'home_repair', title:'Possible faucet repair request', description:'Publicly discovered request that has not yet been claimed or verified by the requester.', helpType:'either', location:{label:'Naperville',lat:41.76,lng:-88.15,precision:'city'}, time:{flexible:true}, confidence:.84, urgency:'normal', dedupeKey:'demo-public-faucet' },
];
export const demoHelpers = [
  { id:'helper_demo_1', displayName:'Alex', home:{label:'Naperville',lat:41.75,lng:-88.15}, radiusMiles:5, categories:['yard','moving','pickup_delivery'], helpTypes:['paid','volunteer'], minimumHourly:18, reliability:.95, verified:true },
  { id:'helper_demo_2', displayName:'Morgan', home:{label:'Naperville',lat:41.78,lng:-88.16}, radiusMiles:4, categories:['moving','assembly','home_repair'], helpTypes:['paid'], minimumHourly:25, reliability:.9, verified:true },
];
